apiVersion: v1
kind: ConfigMap
metadata:
  name: event-booking-config
  namespace: online-event-booking-haleema
data:
  # Booking Service
  BOOKING_PORT: "5003"
  DATABASE_URL: "postgresql://postgres:root@postgres-booking:5432/booking_service_db"
  POSTGRES_URI_BOOKING: "postgres://postgres:root@postgres-booking:5432/booking_service_db"

  # Event Service
  EVENT_PORT: "5002"
  MONGO_URI_EVENT: "mongodb://mongo-event:27017/event_service_db"

  # Frontend Service
  VITE_EVENT_API_URL: "http://localhost:5002/events"
  VITE_BOOKING_API_URL: "http://localhost:5003/bookings"
  VITE_USER_API_URL: "http://localhost:5001/users"
  VITE_NOTIFICATION_API_URL: "http://localhost:5004/notifications"
  VITE_API_BASE_URL: "/api"

  # Notification Service
  NOTIFICATION_PORT: "5004"
  MONGO_URI_NOTIFY: "mongodb://mongo-notify:27017/notification-db"
  RABBITMQ_URL: "amqp://rabbitmq:5672"
  QUEUE_NAME: "booking_notifications"

  # User Service
  USER_PORT: "5001"
  DB_HOST: "postgres-user"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "user_service_db"
  POSTGRES_URI: "postgres://postgres:root@postgres-user:5432/user_service_db"
